name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  version:
    description: "currentVersion"
    required: true
    default: 0  
outputs:
  time: # id of output
    description: 'The time we greeted you'
  newVersion:
    description: 'The new version'  
runs:
  using: 'node12'
  main: 'dist/index.js'
